In [1]:
import pandas as pd

In [2]:
min=pd.read_csv('C:/py/stock_trading_agent/article_df/숙제/민수.csv')

In [4]:
min.iloc[:,1:3]

Title  label
0               국민안전로봇 2021년까지 개발…'로봇물고기' 전철 피할까?      0
1                      '국정원 해킹 의혹' 상임위 앞두고 與野 전초전      0
2   인터넷티비(TV)결합상품 인터넷가입 비교사이트 통해 통신사별 장단점 비교해야 유리      0
3     SKT LG KT 인터넷가입 비교사이트 ‘펭귄통신’ 설치 당일 현금지원 이벤트      0
4                      설 연휴 고향 가는 길 언제 출발해야 덜 막힐까      0
..                                            ...    ...
95                     최태원 SK 회장 다보스서 '사회적 가치' 설파      0
96       항공사부터 박물관까지 MS의 클라우드 세상 한 눈에… '애저 에브리웨어'      0
97                반사이익 '톡톡' 티맵택시 120만 돌파…12배 '폭증'      0
98                    '카풀 논란'에도 카카오택시 호출 12월 최다 ↑      0
99                      LGU+가 시작한 5G 속도전.. 갈길이 멀다      0

[100 rows x 2 columns]

In [ ]:
import numpy as np

In [36]:
np.bincount(min['label'].isna())

array([100], dtype=int64)

In [37]:
min.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  100 non-null    int64 
 1   Title       100 non-null    object
 2   label       100 non-null    int64 
dtypes: int64(2), object(1)
memory usage: 2.5+ KB


In [5]:
you=pd.read_csv('C:/py/stock_trading_agent/article_df/숙제/유희.csv')
you
you.iloc[:,1:3]

Title  label
0               타임워너, 국내 PP 지분 100%로 확대      0
1                     한국서 자율주행차 토론회 열린다      0
2       내일 'LG 워치' 조기출격…'65만원' 이유는?(종합)      0
3   26일 '체험존' 여는 '갤S6'…SKT 영업정지가 복병(종합)     -1
4          AK몰, 4일간의 특가쇼핑찬스 ‘크레이지 4데이즈’      0
..                                  ...    ...
95                [김영무 칼럼]17년 만의 팍스넷 상장      0
96   [마감시황]코스피, 7거래일만에 '숨고르기'…1990선 아래로      0
97  [뉴아시아,지나온 10년 다가올 10년]증시 알파고가 종목 추천      0
98          코스피, 外人 매도세 거세지며 '2000선' 위협      0
99                   코스피, 대형주 부진에 하락 출발     -1

[100 rows x 2 columns]

In [38]:
np.bincount(you['label'].isna())

array([100], dtype=int64)

In [39]:
np.bincount(sora['label'].isna())

array([100], dtype=int64)

In [6]:
sora=pd.read_csv('C:/py/stock_trading_agent/article_df/숙제/소라.csv')
sora
sora.iloc[:,1:3]

Title  label
0   정부, 구글 지도 해외 반출 불허 구글이 보완책 수용 안해 (상보)      0
1              미래부, 2차 유료방송 발전방안 공개토론회 개최      0
2        SKT, 전용폰 구입 고객에 T1 롤드컵 우승 기념품 증정      1
3     '갤S7'사면 페이백 50만원 준다더니제2의 거성 모바일 사태?      0
4          케이블TV 가입자도 내년 1월부터 SKT 요금할인받는다      1
..                                    ...    ...
95         이통3사, LG G4 예약판매 돌입'혜택·이벤트' 듬뿍      1
96         'LG G4' 22일부터 이통3사 예판 액정 무상교체       1
97          '갤S6'로 승부 건 KT지원금 '상한액 수준' 올려      0
98        "엣지 없습니다  S6 품귀에 이통사 이벤트도 '연장'"      1
99                      LG유플러스, 용산 신사옥 시대      0

[100 rows x 2 columns]

In [7]:
str(sora['Title'])

'0     정부, 구글 지도 해외 반출 불허 구글이 보완책 수용 안해 (상보)\n1                미래부, 2차 유료방송 발전방안 공개토론회 개최\n2          SKT, 전용폰 구입 고객에 T1 롤드컵 우승 기념품 증정\n3       \'갤S7\'사면 페이백 50만원 준다더니제2의 거성 모바일 사태?\n4            케이블TV 가입자도 내년 1월부터 SKT 요금할인받는다\n                      ...                  \n95           이통3사, LG G4 예약판매 돌입\'혜택·이벤트\' 듬뿍\n96           \'LG G4\' 22일부터 이통3사 예판 액정 무상교체 \n97            \'갤S6\'로 승부 건 KT지원금 \'상한액 수준\' 올려\n98          "엣지 없습니다  S6 품귀에 이통사 이벤트도 \'연장\'"\n99                        LG유플러스, 용산 신사옥 시대\nName: Title, Length: 100, dtype: object'

In [8]:
hye=pd.read_csv('C:/py/stock_trading_agent/article_df/숙제/혜지.csv')

In [9]:
hye
hye=hye.iloc[:,1:3]

In [10]:
hye

Title  label
0      [굿모닝 증시]마이너스 금리·환율에 대처하는 우리의 자세    0.0
1            현대건설 SK텔레콤과 스마트홈 사업협력 MOU    1.0
2   유비벨록스 자회사 라임아이 디오인터랙티브 합병안 주주총회 승인    0.0
3   [특징주]SGA솔루션즈 애플의 FIDO 인증 제품 지원소식…↑    0.0
4    SK텔레콤 3분기 영업익 4662억..전년비 7.82% 감소   -1.0
..                                 ...    ...
95     박태환·안세현 2019 광주세계수영선수권 홍보대사로 임명    0.0
96  애플 아이폰6s 23일 국내 출시…이전보다 10만원 이상 비싸    0.0
97   SKT '연결의 힘' 캠페인…첫 프로젝트는 '정우 무전여행'    1.0
98         롤챔스 '버프걸' 채림, "인형이야, 사람이야?"    0.0
99                안세현 박태환 코치 '빨' 좀 받을까    0.0

[100 rows x 2 columns]

In [11]:
import numpy as np

In [25]:
np.bincount(hye['label'].isna())

array([98], dtype=int64)

In [21]:
hye.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Title   98 non-null     object 
 1   label   98 non-null     float64
dtypes: float64(1), object(1)
memory usage: 2.3+ KB


In [31]:
hye

Title  label
0      [굿모닝 증시]마이너스 금리·환율에 대처하는 우리의 자세    0.0
1            현대건설 SK텔레콤과 스마트홈 사업협력 MOU    1.0
2   유비벨록스 자회사 라임아이 디오인터랙티브 합병안 주주총회 승인    0.0
3   [특징주]SGA솔루션즈 애플의 FIDO 인증 제품 지원소식…↑    0.0
4    SK텔레콤 3분기 영업익 4662억..전년비 7.82% 감소   -1.0
..                                 ...    ...
95     박태환·안세현 2019 광주세계수영선수권 홍보대사로 임명    0.0
96  애플 아이폰6s 23일 국내 출시…이전보다 10만원 이상 비싸    0.0
97   SKT '연결의 힘' 캠페인…첫 프로젝트는 '정우 무전여행'    1.0
98         롤챔스 '버프걸' 채림, "인형이야, 사람이야?"    0.0
99                안세현 박태환 코치 '빨' 좀 받을까    0.0

[98 rows x 2 columns]

In [29]:
import pandas as pd

In [56]:
hye2 = hye.astype({'label':int})

In [57]:
hye2

Title  label
0      [굿모닝 증시]마이너스 금리·환율에 대처하는 우리의 자세      0
1            현대건설 SK텔레콤과 스마트홈 사업협력 MOU      1
2   유비벨록스 자회사 라임아이 디오인터랙티브 합병안 주주총회 승인      0
3   [특징주]SGA솔루션즈 애플의 FIDO 인증 제품 지원소식…↑      0
4    SK텔레콤 3분기 영업익 4662억..전년비 7.82% 감소     -1
..                                 ...    ...
95     박태환·안세현 2019 광주세계수영선수권 홍보대사로 임명      0
96  애플 아이폰6s 23일 국내 출시…이전보다 10만원 이상 비싸      0
97   SKT '연결의 힘' 캠페인…첫 프로젝트는 '정우 무전여행'      1
98         롤챔스 '버프걸' 채림, "인형이야, 사람이야?"      0
99                안세현 박태환 코치 '빨' 좀 받을까      0

[98 rows x 2 columns]

In [35]:
hye['label'].unique()

array([ 0.,  1., -1.])

In [18]:
np.bincount(hye['Title'].isna())

array([100], dtype=int64)

In [19]:
hye = hye.dropna(axis=0)

In [23]:
hye['label'].value_counts()

 0.0    87
 1.0    10
-1.0     1
Name: label, dtype: int64

In [24]:
hye['label'].unique()

array([ 0.,  1., -1.])

In [15]:
hye.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Title   100 non-null    object 
 1   label   98 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.7+ KB


In [16]:
hjae=pd.read_csv('C:/py/stock_trading_agent/article_df/숙제/희재.csv')
hjae

Unnamed: 0                                              Title  label
0         2379                                 로봇세상에서 돋보인 '엣지컴퓨팅'      1
1         2383                      삼성전자 SKT 등 5G 스마트 팩토리 동맹 '맞손'      1
2         2399                                 5G 주도권 삼성전자 반전 노린다      1
3         2407                       SKT 5G자율주행車 첫선.. K-CITY를 달리다      1
4         2413                            젊어진 SK그룹…...4050 전진 앞으로      1
..         ...                                                ...    ...
78        4176  스웨덴 에릭슨"4차 산업혁명 협력할 韓 스타트업 찾습니다 ,0\r\n4187,SKT...      1
79        4202  CJ헬로비전 작년 영업이익 59.4% 감소한 429억원…"M&A 등 불확실성 해소,...      1
80        4259                                SKT 2019년까지 11조원 투자      1
81        4282                       통신사 커버리지맵 정확도 SKT 1위 '오차 0%'      1
82        4310  크리스마스 맞이 스마트폰 가격 인하…"연말 특수 기대,1\r\n4384,CJ헬로비전...      1

[83 rows x 3 columns]

In [17]:
hjae=hjae.iloc[:,1:3]

In [40]:
hye

Title  label
0      [굿모닝 증시]마이너스 금리·환율에 대처하는 우리의 자세    0.0
1            현대건설 SK텔레콤과 스마트홈 사업협력 MOU    1.0
2   유비벨록스 자회사 라임아이 디오인터랙티브 합병안 주주총회 승인    0.0
3   [특징주]SGA솔루션즈 애플의 FIDO 인증 제품 지원소식…↑    0.0
4    SK텔레콤 3분기 영업익 4662억..전년비 7.82% 감소   -1.0
..                                 ...    ...
95     박태환·안세현 2019 광주세계수영선수권 홍보대사로 임명    0.0
96  애플 아이폰6s 23일 국내 출시…이전보다 10만원 이상 비싸    0.0
97   SKT '연결의 힘' 캠페인…첫 프로젝트는 '정우 무전여행'    1.0
98         롤챔스 '버프걸' 채림, "인형이야, 사람이야?"    0.0
99                안세현 박태환 코치 '빨' 좀 받을까    0.0

[98 rows x 2 columns]

In [41]:
hjae

Title  label
0                                  로봇세상에서 돋보인 '엣지컴퓨팅'      1
1                       삼성전자 SKT 등 5G 스마트 팩토리 동맹 '맞손'      1
2                                  5G 주도권 삼성전자 반전 노린다      1
3                        SKT 5G자율주행車 첫선.. K-CITY를 달리다      1
4                             젊어진 SK그룹…...4050 전진 앞으로      1
..                                                ...    ...
78  스웨덴 에릭슨"4차 산업혁명 협력할 韓 스타트업 찾습니다 ,0\r\n4187,SKT...      1
79  CJ헬로비전 작년 영업이익 59.4% 감소한 429억원…"M&A 등 불확실성 해소,...      1
80                                SKT 2019년까지 11조원 투자      1
81                       통신사 커버리지맵 정확도 SKT 1위 '오차 0%'      1
82  크리스마스 맞이 스마트폰 가격 인하…"연말 특수 기대,1\r\n4384,CJ헬로비전...      1

[83 rows x 2 columns]

In [42]:
sora

Unnamed: 0                                  Title  label
0         4419  정부, 구글 지도 해외 반출 불허 구글이 보완책 수용 안해 (상보)      0
1         4438             미래부, 2차 유료방송 발전방안 공개토론회 개최      0
2         4450       SKT, 전용폰 구입 고객에 T1 롤드컵 우승 기념품 증정      1
3         4462    '갤S7'사면 페이백 50만원 준다더니제2의 거성 모바일 사태?      0
4         4465         케이블TV 가입자도 내년 1월부터 SKT 요금할인받는다      1
..         ...                                    ...    ...
95        6426         이통3사, LG G4 예약판매 돌입'혜택·이벤트' 듬뿍      1
96        6434         'LG G4' 22일부터 이통3사 예판 액정 무상교체       1
97        6444          '갤S6'로 승부 건 KT지원금 '상한액 수준' 올려      0
98        6447        "엣지 없습니다  S6 품귀에 이통사 이벤트도 '연장'"      1
99        6480                      LG유플러스, 용산 신사옥 시대      0

[100 rows x 3 columns]

In [43]:
you

Unnamed: 0                                Title  label
0         6490              타임워너, 국내 PP 지분 100%로 확대      0
1         6505                    한국서 자율주행차 토론회 열린다      0
2         6527      내일 'LG 워치' 조기출격…'65만원' 이유는?(종합)      0
3         6559  26일 '체험존' 여는 '갤S6'…SKT 영업정지가 복병(종합)     -1
4         6565         AK몰, 4일간의 특가쇼핑찬스 ‘크레이지 4데이즈’      0
..         ...                                  ...    ...
95        8789                [김영무 칼럼]17년 만의 팍스넷 상장      0
96        8794   [마감시황]코스피, 7거래일만에 '숨고르기'…1990선 아래로      0
97        8803  [뉴아시아,지나온 10년 다가올 10년]증시 알파고가 종목 추천      0
98        8824          코스피, 外人 매도세 거세지며 '2000선' 위협      0
99        8839                   코스피, 대형주 부진에 하락 출발     -1

[100 rows x 3 columns]

In [44]:
min

Unnamed: 0                                          Title  label
0           60              국민안전로봇 2021년까지 개발…'로봇물고기' 전철 피할까?      0
1           81                     '국정원 해킹 의혹' 상임위 앞두고 與野 전초전      0
2          151  인터넷티비(TV)결합상품 인터넷가입 비교사이트 통해 통신사별 장단점 비교해야 유리      0
3          157    SKT LG KT 인터넷가입 비교사이트 ‘펭귄통신’ 설치 당일 현금지원 이벤트      0
4          162                     설 연휴 고향 가는 길 언제 출발해야 덜 막힐까      0
..         ...                                            ...    ...
95        2301                     최태원 SK 회장 다보스서 '사회적 가치' 설파      0
96        2321       항공사부터 박물관까지 MS의 클라우드 세상 한 눈에… '애저 에브리웨어'      0
97        2366                반사이익 '톡톡' 티맵택시 120만 돌파…12배 '폭증'      0
98        2371                    '카풀 논란'에도 카카오택시 호출 12월 최다 ↑      0
99        2374                      LGU+가 시작한 5G 속도전.. 갈길이 멀다      0

[100 rows x 3 columns]

In [59]:
total= pd.concat([min,you,sora,hye2,hjae])

In [60]:
total

Unnamed: 0                                              Title  label
0         60.0                  국민안전로봇 2021년까지 개발…'로봇물고기' 전철 피할까?      0
1         81.0                         '국정원 해킹 의혹' 상임위 앞두고 與野 전초전      0
2        151.0      인터넷티비(TV)결합상품 인터넷가입 비교사이트 통해 통신사별 장단점 비교해야 유리      0
3        157.0        SKT LG KT 인터넷가입 비교사이트 ‘펭귄통신’ 설치 당일 현금지원 이벤트      0
4        162.0                         설 연휴 고향 가는 길 언제 출발해야 덜 막힐까      0
..         ...                                                ...    ...
78         NaN  스웨덴 에릭슨"4차 산업혁명 협력할 韓 스타트업 찾습니다 ,0\r\n4187,SKT...      1
79         NaN  CJ헬로비전 작년 영업이익 59.4% 감소한 429억원…"M&A 등 불확실성 해소,...      1
80         NaN                                SKT 2019년까지 11조원 투자      1
81         NaN                       통신사 커버리지맵 정확도 SKT 1위 '오차 0%'      1
82         NaN  크리스마스 맞이 스마트폰 가격 인하…"연말 특수 기대,1\r\n4384,CJ헬로비전...      1

[481 rows x 3 columns]

In [65]:
del total['Unnamed: 0']

In [66]:
total

Title  label
0                   국민안전로봇 2021년까지 개발…'로봇물고기' 전철 피할까?      0
1                          '국정원 해킹 의혹' 상임위 앞두고 與野 전초전      0
2       인터넷티비(TV)결합상품 인터넷가입 비교사이트 통해 통신사별 장단점 비교해야 유리      0
3         SKT LG KT 인터넷가입 비교사이트 ‘펭귄통신’ 설치 당일 현금지원 이벤트      0
4                          설 연휴 고향 가는 길 언제 출발해야 덜 막힐까      0
..                                                ...    ...
78  스웨덴 에릭슨"4차 산업혁명 협력할 韓 스타트업 찾습니다 ,0\r\n4187,SKT...      1
79  CJ헬로비전 작년 영업이익 59.4% 감소한 429억원…"M&A 등 불확실성 해소,...      1
80                                SKT 2019년까지 11조원 투자      1
81                       통신사 커버리지맵 정확도 SKT 1위 '오차 0%'      1
82  크리스마스 맞이 스마트폰 가격 인하…"연말 특수 기대,1\r\n4384,CJ헬로비전...      1

[481 rows x 2 columns]

In [67]:
total['label'].unique()

array([ 0,  1, -1], dtype=int64)

In [73]:
test_data = total

stopwords = ['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']

import konlpy
from konlpy.tag import Okt

okt = Okt()
#test_data
X_test = []
test_data = test_data.dropna()

for sentence in test_data['Title']:
  #print(sentence)
  #break;
    if sentence is not None:
        temp_X = []
        # 토큰화
        temp_X = okt.morphs(sentence, stem=True) 
        # 불용어 제거
        temp_X = [word for word in temp_X if not word in stopwords] 
        X_test.append(temp_X)

words = []
for tokens in X_test:
    for token in tokens:  
        words.append(token)


#X_test

In [74]:
from collections import Counter

count = Counter(words)

tag_count = []
tags = []

for n, c in count.most_common(500):
    dics = {'tag': n, 'count': c}

    if len(dics['tag']) >= 2 and len(tags) <= 250:
        tag_count.append(dics)
        tags.append(dics['tag'])
    
for tag in tag_count:
    print(" {:<14}".format(tag['tag']), end='\t')
    print("{}".format(tag['count']))

 SKT           	97
 SK            	65
 코스피           	47
 텔레콤           	40
 이통            	32
 출시            	28
 종합            	24
 삼성            	23
 아이폰           	23
 KT            	20
 통신            	19
 
            	17
 LG            	14
 …"            	14
 보다            	13
 만에            	13
 회복            	12
 전자            	12
 되다            	12
 스마트           	12
 인하            	12
 ..            	12
 개다            	12
 상승            	12
 기관            	12
 에서            	11
 부터            	11
 요금            	11
 협력            	11
 국내            	11
 오다            	11
 마감            	11
 까지            	10
 LGU           	10
 서비스           	10
 '…            	10
 그룹            	10
 통법            	10
 컨콜            	10
 시대            	10
 데이터           	10
 AI            	10
 가입자           	10
 외국인           	10
 코스닥           	10
 갤럭시           	9
 효과            	9
 나서다           	9
 시장            	9
 금제            	9
 사업            	9
 증시            	9
 통신비           	9
 최

In [80]:
import requests
import re
import pandas as pd

TEST용 사전 불러오기

In [84]:
train_data =pd.read_csv('C:/py/stock_trading_agent/senti/title_for_sentiment/dic_train_dataset.csv')


In [90]:
train_data

Title  label
0               與 영남주자들 “신종 코로나 추경 검토해야”      0
1         전기차-충전기 제조사와 함께하는 '상호운용성 테스티벌'      0
2        "정부, 저공해차 안 만드는 대기업에 패널티 강화 추진"      1
3      '시스템반도체 팹리스' 후속조치 본격화…현장과 소통행보 시작      1
4          외국인, 보름간 韓 주식 2.4兆 매수…반도체가 절반      0
...                                  ...    ...
21475         황보성일, 男핸드볼 SK하이닉스 코치로 새 도전      0
21476         남자 핸드볼 SK하이닉스, 충북으로 연고지 선정      1
21477      선수들이 면접을?…신생팀 SK하이닉스의 색다른 테스트      0
21478            SK하이닉스 남자핸드볼구단 코칭스태프 확정      0
21479            SK하이닉스, 남자 핸드볼 실업 구단 창단      0

[21480 rows x 2 columns]

In [87]:
train_data=train_data.iloc[:,1:3]

In [88]:
total.to_csv('C:/py/stock_trading_agent/senti/title_for_sentiment/total_test.csv')

In [89]:
import matplotlib.pyplot as plt

In [91]:
train_data['label'].value_counts().plot(kind='bar')

<AxesSubplot:>

In [93]:
print(train_data.groupby('label').size().reset_index(name='count'))

   label  count
0     -1   2540
1      0   9652
2      1   9288


## 모델 만들기 위한 전처리 작업

In [94]:
stopwords = ['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']

## 토큰화 : 의미있는 단어로 나눠준다

In [95]:
import konlpy
from konlpy.tag import Okt

#테스트용 사전
for_dic_test=pd.read_csv('C:/py/stock_trading_agent/senti/title_for_sentiment/dic_train_dataset.csv')
train_data=for_dic_test

okt = Okt()
X_train = []
for sentence in ㅌ:
    temp_X = [] 
    temp_X = okt.morphs(sentence, stem=True) # 토큰화
    temp_X = [word for word in temp_X if not word in stopwords] # 불용어 제거
    X_train.append(temp_X)

X_test = []
for sentence in test_data['Title']:
    temp_X = []
    temp_X = okt.morphs(sentence, stem=True) # 토큰화
    temp_X = [word for word in temp_X if not word in stopwords] # 불용어 제거
    X_test.append(temp_X)


In [96]:
X_train

[['與', '영남', '주자', '“', '신종', '코로나', '추경', '검토', '”'],
 ['전기차', '-', '충전기', '제', '조사', '함께', "'", '상호', '운용', '성', '테스', '티벌', "'"],
 ['"',
  '정부',
  ',',
  '저',
  '공해',
  '차',
  '안',
  '만들다',
  '대기업',
  '패널',
  '티',
  '강화',
  '추진',
  '"'],
 ["'",
  '시스템',
  '반도체',
  '팹리스',
  "'",
  '후속',
  '조치',
  '본격',
  '화',
  '…',
  '현장',
  '소통',
  '행보',
  '시작'],
 ['외국인', ',', '보름', '간', '韓', '주식', '2.4', '兆', '매수', '…', '반도체', '절반'],
 ['與',
  '"',
  '한국',
  '당',
  "'",
  '박영선',
  '흠집',
  '내기',
  "'",
  '넘다',
  '…',
  '강력',
  '대응',
  '"'],
 ['한국',
  '당',
  '산',
  '자위',
  '“',
  '박영선',
  '남편',
  ',',
  '현대',
  '·',
  '기아차',
  '막대',
  '수임료',
  '추정',
  '”'],
 ["'",
  '텔루',
  '라이드',
  "'",
  '생산',
  '공장',
  '찾다',
  '韓',
  '·',
  '美',
  '대사',
  '"',
  '기아차',
  ',',
  '현지',
  '경제',
  '살리다',
  '"'],
 ['[', '포토', ']', '김현종', '본부장', ',', '美', '상원의원', "'", '車', '232조', "'", '면담'],
 ['하태경', '“', '한국', 'GM', '노조', ',', '또', '파업', '…', '명백하다', '자살', '행위', '”'],
 ['조선업',
  '이다',
  '車',
  '부품',
  '기업',
  '3.5조원',

## 토큰화한 단어. 컴퓨터 인식 가능하도록 정수 인코딩

In [97]:
from keras.preprocessing.text import Tokenizer
max_words = 35000 
tokenizer = Tokenizer(num_words = max_words)
tokenizer.fit_on_texts(X_train) 
X_train = tokenizer.texts_to_sequences(X_train) 
X_test = tokenizer.texts_to_sequences(X_test)

In [98]:
X_test[:3]

[[1739, 544, 1138, 1863, 95, 215, 107, 1138, 2, 2019, 79],
 [2, 8090, 2194, 2, 61, 244],
 [10469,
  6751,
  22,
  619,
  18,
  5243,
  814,
  10469,
  2699,
  4570,
  9569,
  1576,
  1187,
  10988,
  4570,
  2754]]

## one-hot encoding

In [99]:
import numpy as np
y_train = []
y_test = []
for i in range(len(train_data['label'])):
    if train_data['label'].iloc[i] == 1:
        y_train.append([0, 0, 1]) 
    elif train_data['label'].iloc[i] == 0:
        y_train.append([0, 1, 0]) 
    elif train_data['label'].iloc[i] == -1:
        y_train.append([1, 0, 0]) 
        
for i in range(len(test_data['label'])):
    if test_data['label'].iloc[i] == 1:
        y_test.append([0, 0, 1]) 
    elif test_data['label'].iloc[i] == 0:
        y_test.append([0, 1, 0]) y_test
    elif test_data['label'].iloc[i] == -1:
        y_test.append([1, 0, 0]) 
        
y_train=np.array(y_train)
y_test=np.array(y_test)

In [105]:
test_data

Title  label
0                   국민안전로봇 2021년까지 개발…'로봇물고기' 전철 피할까?      0
1                          '국정원 해킹 의혹' 상임위 앞두고 與野 전초전      0
2       인터넷티비(TV)결합상품 인터넷가입 비교사이트 통해 통신사별 장단점 비교해야 유리      0
3         SKT LG KT 인터넷가입 비교사이트 ‘펭귄통신’ 설치 당일 현금지원 이벤트      0
4                          설 연휴 고향 가는 길 언제 출발해야 덜 막힐까      0
..                                                ...    ...
78  스웨덴 에릭슨"4차 산업혁명 협력할 韓 스타트업 찾습니다 ,0\r\n4187,SKT...      1
79  CJ헬로비전 작년 영업이익 59.4% 감소한 429억원…"M&A 등 불확실성 해소,...      1
80                                SKT 2019년까지 11조원 투자      1
81                       통신사 커버리지맵 정확도 SKT 1위 '오차 0%'      1
82  크리스마스 맞이 스마트폰 가격 인하…"연말 특수 기대,1\r\n4384,CJ헬로비전...      1

[481 rows x 2 columns]

In [100]:
y_test

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

## 모델만들기 & 학습

In [101]:
from keras.layers import Embedding, Dense, LSTM
from keras.models import Sequential
from keras.preprocessing.sequence import pad_sequences

max_len = 20 # pad_sequesces이용, 전체 데이터의 길이를 20로 맞춘다
X_train = pad_sequences(X_train, maxlen=max_len)
X_test = pad_sequences(X_test, maxlen=max_len)

In [102]:
model = Sequential()
model.add(Embedding(max_words, 100))
model.add(LSTM(128))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy']) 
history = model.fit(X_train, y_train, epochs=10, batch_size=10, validation_split=0.1)

Epoch 1/10
1934/1934 [==============================] - 44s 23ms/step - loss: 0.2990 - accuracy: 0.8912 - val_loss: 0.1190 - val_accuracy: 0.9623
Epoch 2/10
1934/1934 [==============================] - 43s 22ms/step - loss: 0.0719 - accuracy: 0.9814 - val_loss: 0.0684 - val_accuracy: 0.9823
Epoch 3/10
1934/1934 [==============================] - 43s 22ms/step - loss: 0.0455 - accuracy: 0.9896 - val_loss: 0.0730 - val_accuracy: 0.9814
Epoch 4/10
1934/1934 [==============================] - 42s 22ms/step - loss: 0.0371 - accuracy: 0.9920 - val_loss: 0.0821 - val_accuracy: 0.9818
Epoch 5/10
1934/1934 [==============================] - 43s 22ms/step - loss: 0.0302 - accuracy: 0.9938 - val_loss: 0.0740 - val_accuracy: 0.9832
Epoch 6/10
1934/1934 [==============================] - 45s 23ms/step - loss: 0.0258 - accuracy: 0.9946 - val_loss: 0.0750 - val_accuracy: 0.9837
Epoch 7/10
1934/1934 [==============================] - 45s 23ms/step - loss: 0.0258 - accuracy: 0.9950 - val_loss: 0.0833 -

## Optimizer 아담으로 바꾼 애!

In [106]:
model2 = Sequential()
model2.add(Embedding(max_words, 100))
model2.add(LSTM(128))
model2.add(Dense(3, activation='softmax'))
model2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']) 
history = model2.fit(X_train, y_train, epochs=10, batch_size=10, validation_split=0.1)

Epoch 1/10
1934/1934 [==============================] - 80s 42ms/step - loss: 0.2081 - accuracy: 0.9268 - val_loss: 0.0665 - val_accuracy: 0.9809
Epoch 2/10
1934/1934 [==============================] - 77s 40ms/step - loss: 0.0303 - accuracy: 0.9911 - val_loss: 0.0691 - val_accuracy: 0.9865
Epoch 3/10
1934/1934 [==============================] - 74s 38ms/step - loss: 0.0135 - accuracy: 0.9961 - val_loss: 0.0516 - val_accuracy: 0.9916
Epoch 4/10
1934/1934 [==============================] - 77s 40ms/step - loss: 0.0061 - accuracy: 0.9981 - val_loss: 0.0624 - val_accuracy: 0.9902
Epoch 5/10
1934/1934 [==============================] - 81s 42ms/step - loss: 0.0046 - accuracy: 0.9987 - val_loss: 0.0671 - val_accuracy: 0.9865
Epoch 6/10
1934/1934 [==============================] - 81s 42ms/step - loss: 0.0034 - accuracy: 0.9990 - val_loss: 0.0778 - val_accuracy: 0.9879
Epoch 7/10
1934/1934 [==============================] - 80s 41ms/step - loss: 0.0044 - accuracy: 0.9988 - val_loss: 0.0760 -

train = 딕셔너리  => 모델 만들때는 train 데이터로 만듬


test data = total(데이터 만들어준거 합친것)
긍부정 예측을 해주는것 



## 모델 평가

In [107]:
print("\n 테스트 정확도 : {:.2f}%".format(model.evaluate(X_test,y_test)[1]*100))

16/16 [==============================] - 0s 4ms/step - loss: 7.6181 - accuracy: 0.5135

 테스트 정확도 : 51.35%


In [108]:
print("\n 테스트 정확도 : {:.2f}%".format(model2.evaluate(X_test,y_test)[1]*100))

16/16 [==============================] - 0s 5ms/step - loss: 6.9503 - accuracy: 0.5177

 테스트 정확도 : 51.77%


# 한계
1. dataset 불균형(-1이 4배 정도 적음)
2. 긍정부정중립 label 일부 주관적